### ISSUE TITLE
The default map sometimes loads when a custom one should

### ISSUE THREAD

**Issue by ghost** [Insprill/dv-mapify#54]
When i eventually get to load up my custom maps in " Career Mode" the in game map uses the default DV map as-well, and my stations aren't visible. Any ideas on how to fix this one?

Also i cant get jobs to spawn, even when i methodically set up my stations for jobs inbound and outbound.

Cheers.

**Comment by t0stiman** [comment]
Loading a custom map in career mode works for me, so it's probably fixed after the last Mapify release.

We plan to release an update for Mapify soon, I suggest you wait for that and let us know if these issues persist then.

**Comment by Kelticcol** [comment]
Ok, thanks for the update.
I do have the latest update aswell.
Looking forward to the update 👍👍

**Comment by Insprill** [comment]
There's been an issue since Simulator where the main menu state isn't properly tracked, causing the selected map not to get loaded. The way the state is tracked is a little hacky, but I'm not sure what the best approach would be to track it differently since DV has the two main parameters, session and difficultly, hardcoded in the UI methods.

**Comment by t0stiman** [comment]
This bug does not occur anymore. Or at least, I can't replicate it.
